### ISSUE TITLE
Getting 'Not Found' error

### ISSUE THREAD

**Issue by MarketingMandy** [aug-riedinger/google-docs-publisher#51]
Hello

I've been using this for years and love it so thank you, but when I was checking something over, I realised my links now say 'Not Found' in the top left. I double checked and the original documents haven't been deleted, and I tried it again with another document and it isn't working for new ones either. I tried it on the Mac in both Chrome and Safari. Is there an issue? Sample link and screenshot: https://gdoc.pub/doc/1cY6qgS5ylRF8FDTD8zMr8wOI4o0Wwdtou3smB10gOp8#?usp=sharing

<img width="1136" alt="Screenshot 2020-12-01 at 11 08 54" src="https://user-images.githubusercontent.com/64634014/100733140-a1bca200-33c5-11eb-876e-b3a3178e074d.png">

**Comment by brandongoodwin02** [comment]
I'm also getting the same "Not Found" response on many of my published pages. It's not on every page, but it is appearing on several of them.

**Comment by augnustin** [comment]
Hello Brandon,

Apologies for this. I did make a small update which broke some documents.
It is now fixed, you can check it out.

Best,

Augustin Riedinger

---
Want to hire a Web Freelancer? Checkout my Portfolio
<http://augustin-riedinger.fr>.
Looking for a place to work? Copass <https://copass.org/> offers flexible
coworking at its best.
No music inspiration? NovaTube <http://novatu.be> brings good music without
interruption.
Need to publish documents on the web easily? Try Google Doc Publisher
<http://gdoc.pub>.


Le mar. 1 déc. 2020 à 15:18, brandongoodwin02 <notifications@github.com> a
écrit :

**Comment by MarketingMandy** [comment]
Thanks, Augustin - all my links are working now!

**Comment by glittle** [comment]
@augnustin  I'm still getting "Not Found".  I've tried recreating the link, to no avail.

**Comment by augnustin** [comment]
@glittle Please send me the URL of your document at: https://www.augustin-riedinger.fr/contact

**Comment by CarrieBush** [comment]
Our link is unreliable.  We often get the "not found" message.  Sometimes a refresh helps but not always.  https://gdoc.pub/doc/e/2PACX-1vTQhVfS91iFmDK3gSLu9pE5fKkW1ThpvDKP1WZ-GuwxvuYIRDjBjqAQPV66WJSwTM-bbnZzoVQ0Zfd3   I am bummed because I love the way it looks when I can see it.

**Comment by augnustin** [comment]
I understand your concern, but unfortunately I hardly can fix anything if I can't reproduce the issue deterministically so I don't really see what I can do to help. :/

**Comment by CarrieBush** [comment]
Thank you for your reply. I am in a currently in a meeting with 20 other instructional technology specialists throughout the state of Delaware and I shared the link with them.  Everyone had trouble getting to it seamlessly.  Weird. I’m glad it worked for you.

Sent from iPhone
________________________________

**Comment by MandyHole** [comment]
Hi - just to say that we are getting this issue again from time to time as well. It doesn't work and then a few minutes later it does although nothing has changed. This has been the case for several colleagues across a few different documents...

**Comment by augnustin** [comment]
Hello all,
This feedback from multiple users interrogated me. I checked and it seems like there is an issue. I'm currently investigating and will let you know once it is fixed!
Apologies for the inconvenience.

**Comment by augnustin** [comment]
I just made an update on my server. It seems like it is working properly now. Do you guys confirm?

**Comment by CarrieBush** [comment]
Thanks Augustin, So far so good from what I can tell.  ☺
When your publishing tool didn’t work, I ended up embedding my Google Doc on a Google Site.   So I now have alternate solution.

Carrie

Carrie Bush
(she/her/hers)
Digital Resource Teacher
Caesar Rodney School District
302-697-2173 x129
https://tinyurl.com/bushandboulden

**Comment by MandyHole** [comment]
As far as I can tell, it's working, but I emailed a few colleagues to keep their eyes out. Thanks for fixing it - we will let you know if we see the error again.
